---
title: "Reproducible Research: Peer Assessment 1"
author: A. Gray
---


## Loading and preprocessing the data
activity <- read.csv("activity.csv")
activity$day <- weekdays(as.Date(activity$date))
activity$DateTime<- as.POSIXct(activity$date, format="%Y-%m-%d")


## What is mean total number of steps taken per day?
Summarize total steps per date
sumTable <- aggregate(activity$steps ~ activity$date, FUN=sum, )
colnames(sumTable)<- c("Date", "Steps")

Creating the historgram of total steps per day
hist(sumTable$Steps, breaks=5, xlab="Steps", main = "Total Steps Per Day")

Mean of Steps
as.integer(mean(sumTable$Steps))

Median of Steps
as.integer(median(sumTable$Steps))


## What is the average daily activity pattern?
Clean out nas
cleanDat <- activity[!is.na(activity$steps),]

Create average number of steps per interval
intTable <- ddply(cleanDat, .(interval), summarize, Avg = mean(steps))

Create line plot of average number of steps per interval
p <- ggplot(intTable, aes(x=interval, y=Avg), xlab = "Interval", ylab="Average Number of Steps")
p + geom_line()+xlab("Interval")+ylab("Average Number of Steps")+ggtitle("Average Number of Steps per Interval")


## Imputing missing values
Create the average number of steps per weekday and interval
avgTable <- ddply(cleanDat, .(interval, day), summarize, Avg = mean(steps))

Create dataset with all NAs for substitution
naDat<- activity[is.na(activity$steps),]

Merge NA data with average weekday interval for substitution
newDat<-merge(naDat, avgTable, by=c("interval", "day"))

Reorder the new substituded data in the same format as clean data set
newDat2<- newDat[,c(6,4,1,2,5)]
colnames(newDat2)<- c("steps", "date", "interval", "day", "DateTime")

Merge the NA averages and non NA data together
mergeDat <- rbind(cleanDat, newDat2)


## Are there differences in activity patterns between weekdays and weekends?
Create sum of steps per date to compare with step 1
sumTable2 <- aggregate(mergeDat$steps ~ mergeDat$date, FUN=sum, )
colnames(sumTable2)<- c("Date", "Steps")

Create histogram of total steps per day, categorized by data set to show impact
hist(sumTable2$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day with NAs Fixed", col="Black")
hist(sumTable$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day with NAs Fixed", col="Grey", add=T)
legend("topright", c("Imputed Data", "Non-NA Data"), fill=c("black", "grey") )

Create new category based on the days of the week
mergeDat$DayCategory <- ifelse(mergeDat$day %in% c("Saturday", "Sunday"), "Weekend", "Weekday")

Summarize data by interval and type of day
intTable2 <- ddply(mergeDat, .(interval, DayCategory), summarize, Avg = mean(steps))

Plot data in a panel plot
xyplot(Avg~interval|DayCategory, data=intTable2, type="l",  layout = c(1,2),
       main="Average Steps per Interval Based on Type of Day", 
       ylab="Average Number of Steps", xlab="Interval")



